2024-05-10 02:44:15|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2024-05-10 02:44:15|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2024-05-10 02:44:15|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
2024-05-10 02:44:15|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2024-05-10 02:44:15|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2024-05-10 04:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
2024-05-10 04:00:00|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2024-05-10 07:52:54|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 08:04:27|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E12 - 012 - The Eunuch and the Courtesan [Bluray-1080p][10bit][x265][Opus 2.0][JA]-MTBB.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 820, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 08:04:28|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2024-05-10 12:59:21|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
2024-05-10 13:52:54|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E12 - 012 - The Eunuch and the Courtesan [Bluray-1080p][10bit][x265][Opus 2.0][JA]-MTBB.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 820, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 14:04:28|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2024-05-10 19:52:54|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E01 - 001 - Re-Born [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E02 - 002 - Re-D Bear [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E03 - 003 - Re-Use [v2 HDTV-1080p v2][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E04 - 004 - Re-Ject [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E05 - 005 - Re-Ady [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv') trying to get video information for this file: /data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/Re-Monster (2024) [imdbid-tt31514720]/Season 1/Re-Monster (2024) - S01E06 - 006 - Re-Medy [HDTV-1080p][8bit][x264][AAC 2.0][JA]-SubsPlease.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E12 - 012 - The Eunuch and the Courtesan [Bluray-1080p][10bit][x265][Opus 2.0][JA]-MTBB.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 820, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E13 - 013 - Serving in the Outer Court [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E14 - 014 - The New Pure Consort [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:27|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E15 - 015 - Raw Fish [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E16 - 016 - Lead [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E17 - 017 - A Jaunt Around Town [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E18 - 018 - Lakan [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E19 - 019 - Chance or Something More [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E20 - 020 - Thornapple [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E21 - 021 - How to Buy Out a Contract [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E22 - 022 - Blue Roses [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E23 - 023 - Balsam and Woodsorrel [WEBDL-1080p][8bit][x264][EAC3 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|ERROR   |root                            |BAZARR Error ([Errno 2] No such file or directory: '/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv') trying to get video information for this file: /data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv|'Traceback (most recent call last):\n  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 849, in scan_video\n    video.size = os.path.getsize(hash_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen genericpath>", line 50, in getsize\nFileNotFoundError: [Errno 2] No such file or directory: \'/data/media/anime/The Apothecary Diaries (2023) [imdbid-tt26743760]/Season 1/The Apothecary Diaries (2023) - S01E24 - 024 - Jinshi and Maomao [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-LostYears.mkv\''|
2024-05-10 20:04:28|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2024-05-10 21:40:35|INFO    |root                            |BAZARR Running cache maintenance|
2024-05-10 21:55:23|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2024-05-10 21:55:23|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
2024-05-10 21:55:23|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2024-05-10 21:55:24|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2024-05-10 21:55:24|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
